# Generated by Django 3.2.3 on 2021-06-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meduza', '0002_alter_notification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.AddField(
            model_name='notification',
            name='hour',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
