# Generated by Django 3.2.3 on 2021-06-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meduza', '0003_auto_20210607_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='hour',
            new_name='godzina',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='medication',
            new_name='lek',
        ),
    ]
